### ISSUE TITLE
ESP8266 Arduino Core I2Cdev.cpp lacking definition of min(a, b)

### ISSUE THREAD

**Issue by jmseight** [jrowberg/i2cdevlib#411]
I am getting a problem when I try to compile software for ESP8266.  
```

Arduino: 1.8.5 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Build options changed, rebuilding all
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp: In static member function 'static int8_t I2Cdev::readBytes(uint8_t, uint8_t, uint8_t, uint8_t*, uint16_t)':
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:276:75: error: no matching function for call to 'min(uint8_t&, int)'
             for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) {
                                                                           ^
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:276:75: note: candidates are:
In file included from /Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/algorithm:62:0,
                 from /Users/hyeh/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/cores/esp8266/Arduino.h:255,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.h:77,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:46:
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algo.h:4226:5: note: template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algo.h:4226:5: note:   template argument deduction/substitution failed:
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:276:75: note:   mismatched types 'std::initializer_list<_Tp>' and 'unsigned char'
             for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) {
                                                                           ^
In file included from /Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/algorithm:62:0,
                 from /Users/hyeh/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/cores/esp8266/Arduino.h:255,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.h:77,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:46:
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algo.h:4221:5: note: template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algo.h:4221:5: note:   template argument deduction/substitution failed:
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:276:75: note:   mismatched types 'std::initializer_list<_Tp>' and 'unsigned char'
             for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) {
                                                                           ^
In file included from /Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/algorithm:61:0,
                 from /Users/hyeh/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/cores/esp8266/Arduino.h:255,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.h:77,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:46:
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algobase.h:239:5: note: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algobase.h:239:5: note:   template argument deduction/substitution failed:
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:276:75: note:   deduced conflicting types for parameter 'const _Tp' ('unsigned char' and 'int')
             for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) {
                                                                           ^
In file included from /Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/algorithm:61:0,
                 from /Users/hyeh/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/cores/esp8266/Arduino.h:255,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.h:77,
                 from /Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:46:
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algobase.h:193:5: note: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^
/Users/hyeh/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/stl_algobase.h:193:5: note:   template argument deduction/substitution failed:
/Users/hyeh/Documents/Arduino/libraries/I2Cdev/I2Cdev.cpp:276:75: note:   deduced conflicting types for parameter 'const _Tp' ('unsigned char' and 'int')
             for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) {
                                                                           ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
processing.app.SerialException: Error opening serial port '/dev/cu.wchusbserial1410'.
	at processing.app.Serial.<init>(Serial.java:147)
	at processing.app.Serial.<init>(Serial.java:82)
	at processing.app.SerialMonitor$4.<init>(SerialMonitor.java:101)
	at processing.app.SerialMonitor.open(SerialMonitor.java:101)
	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:104)
	at processing.app.Editor.resumeOrCloseSerialMonitor(Editor.java:2218)
	at processing.app.Editor.access$2200(Editor.java:79)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2196)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jssc.SerialPortException: Port name - /dev/cu.wchusbserial1410; Method name - openPort(); Exception type - Port not found.
	at jssc.SerialPort.openPort(SerialPort.java:167)
	at processing.app.Serial.<init>(Serial.java:136)
	... 8 more
Error opening serial port '/dev/cu.wchusbserial1410'.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


```
After adding the following near the beginning of I2Cdev.cpp, the compilation works.
`#define min(a,b) ((a) < (b) ? (a) : (b))`

**Comment by jmseight** [comment]
Sorry this was corrected at https://github.com/jrowberg/i2cdevlib
I wish the new libraries were the ones that show up when I searched at the beginning.
